Document: rivendell
Title: Debian rivendell Manual
Author: <insert document author here>
Abstract: This manual describes what rivendell is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/rivendell/rivendell.sgml.gz

Format: postscript
Files: /usr/share/doc/rivendell/rivendell.ps.gz

Format: text
Files: /usr/share/doc/rivendell/rivendell.text.gz

Format: HTML
Index: /usr/share/doc/rivendell/html/index.html
Files: /usr/share/doc/rivendell/html/*.html
