usr/lib/rivendell/*.cgi usr/lib/cgi-bin/rivendell
usr/lib/rivendell/*.gif usr/lib/cgi-bin/rivendell
usr/lib/rivendell/*.html usr/lib/cgi-bin/rivendell
usr/lib/rivendell/*.js usr/lib/cgi-bin/rivendell
usr/lib/rivendell/*.mp3 usr/lib/cgi-bin/rivendell
usr/lib/rivendell/*.png usr/lib/cgi-bin/rivendell
usr/lib/rivendell/*.xml usr/lib/cgi-bin/rivendell

debian/apache-2.2.conf etc/rivendell
debian/apache-2.4.conf etc/rivendell